name: "Revoke token"
description: "Revoke token"

inputs:
  url:
    description: "Url vault"
    required: true
  vault_token:
    descrption: "Vault Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Revoke token
      run: |
        curl --fail -X POST -s -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" --write-out "%{http_code}" \
        ${{ inputs.url }}/v1/auth/token/revoke-self
