name: Check action

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  vault:
    runs-on: ubuntu-latest
    outputs:
      ssh_user: ${{ steps.vault.outputs.ssh_user }}
      ssh_host: ${{ steps.vault.outputs.ssh_host }}
      ssh_port: ${{ steps.vault.outputs.ssh_port }}
      ssh_key: ${{ steps.vault.outputs.ssh_key }}
    steps:
      - name: Repository Name
        id: repository
        run: echo "name=${GITHUB_REPOSITORY#*/}" >> ${GITHUB_OUTPUT}

      - name: Get secrets in vault
        uses: hashicorp/vault-action@v2
        id: vault
        with:
          url: ${{ secrets.VAULT_URL }}
          role: ${{ steps.repository.outputs.name }}
          method: jwt
          exportToken: true
          secrets: |
            secrets/data/GitHub/ssh-workflow user | ssh_user ;
            secrets/data/GitHub/ssh-workflow host | ssh_host ;
            secrets/data/GitHub/ssh-workflow port | ssh_port ;
            secrets/data/GitHub/ssh-workflow key | ssh_key ;

  check-action-directly:
    runs-on: ubuntu-latest
    needs: vault
    steps:
      - uses: actions/checkout@v3

      - name: Test Remote command directly
        id: ssh
        uses: mnival/ssh-remote-commands-action@main
        with:
          ssh_host: ${{ jobs.vault.outputs.ssh_host }}
          ssh_user: ${{ jobss.vault.outputs.ssh_user }}
          ssh_key: ${{ jobss.vault.outputs.ssh_key }}
          ssh_port: ${{ steps.vault.outputs.ssh_port }}
          ssh_commands: echo "Test Remote command directly"

      - name: Test after init
        uses: mnival/ssh-remote-commands-action@main
        with: 
          ssh_host_alias: ${{ steps.ssh.outputs.ssh_host_alias }}
          ssh_commands: echo "Test after init"

  check-action-after-config:
    runs-on: ubuntu-latest
    needs: vault
    steps:
      - uses: actions/checkout@v3

      - name: SSH Config
        id: ssh
        uses: mnival/ssh-config-action@v0.0.2
        with:
          ssh_host: ${{ jobs.vault.outputs.ssh_host }}
          ssh_user: ${{ jobss.vault.outputs.ssh_user }}
          ssh_key: ${{ jobss.vault.outputs.ssh_key }}
          ssh_port: ${{ steps.vault.outputs.ssh_port }}

      - name: Test Remote Command
        uses: mnival/ssh-remote-commands-action@main
        with:
          ssh_host_alias: ${{ steps.ssh.outputs.ssh_host_alias }}
          ssh_commands: echo "Test Remote Command"
          ssh_args: -T
